workspace(name = "bazel_workspaces")

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../dist/build_bazel_rules_nodejs/release",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "yarn_install")

yarn_install(
    name = "npm",
    data = [
        "@bazel_workspaces//:npm/test_workspace/WORKSPACE",
        "@bazel_workspaces//:npm/test_workspace/package.json",
        "@bazel_workspaces//:npm/test_workspace/src/BUILD.bazel",
        "@bazel_workspaces//:npm/test_workspace/src/test.spec.js",
        "@bazel_workspaces//:npm/test_workspace/yarn.lock",
    ],
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")

install_bazel_dependencies()
