load("//:defs.bzl", "js_library")

js_library(
    name = "android-chrome-192x192_png",
    srcs = ["android-chrome-192x192.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "android-chrome-512x512_png",
    srcs = ["android-chrome-512x512.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "apple-touch-icon_png",
    srcs = ["apple-touch-icon.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "favicon-16x16_png",
    srcs = ["favicon-16x16.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "favicon-32x32_png",
    srcs = ["favicon-32x32.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "mstile-150x150_png",
    srcs = ["mstile-150x150.png"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "safari-pinned-tab_svg",
    srcs = ["safari-pinned-tab.svg"],
    visibility = ["//visibility:public"],
)
