workspace(name = "e2e_nodejs_host")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "493990db2d49b9a17d10249a40ef28ed308b9a56431861cf5767e49a9e052a6f",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.7.4/rules_nodejs-5.7.4.tar.gz"],
)

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")
load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")
load("@rules_nodejs//nodejs:yarn_repositories.bzl", "yarn_repositories")

# Create the default node toolchain using node_repositories
node_repositories(
    node_version = "12.12.0",
)

# Create additional parallel toolchains using explicit nodejs_register_toolchains targets
nodejs_register_toolchains(
    name = "node14",
    node_version = "14.19.0",
)

nodejs_register_toolchains(
    name = "node16_nvmrc",
    use_nvmrc = "//:.nvmrc",
)

yarn_repositories(
    name = "yarn_node14",
    node_repository = "node14",
)

yarn_repositories(
    name = "yarn_node16_nvmrc",
    node_repository = "node16_nvmrc",
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    package_json_replace = {
        "scripts.postinstall": "node -e \"require('assert').equal(process.version, 'v12.12.0')\"",
    },
    yarn_lock = "//:yarn.lock",
)

yarn_install(
    name = "npm_node14",
    node_repository = "node14",
    package_json = "//:package.json",
    package_json_replace = {
        "scripts.postinstall": "node -e \"require('assert').equal(process.version, 'v14.19.0')\"",
    },
    yarn = "@yarn_node14//:bin/yarn",
    yarn_lock = "//:yarn.lock",
)

yarn_install(
    name = "npm_node16_nvmrc",
    node_repository = "node16_nvmrc",
    package_json = "//:package.json",
    package_json_replace = {
        "scripts.postinstall": "node -e \"require('assert').equal(process.version, 'v16.13.2')\"",
    },
    yarn = "@yarn_node16_nvmrc//:bin/yarn",
    yarn_lock = "//:yarn.lock",
)
