load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
    ],
)

local_repository(
    name = "rules_nodejs",
    path = "../..",
)

load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")

# Create the default node toolchain
nodejs_register_toolchains()

# Create additional parallel toolchains using explicit nodejs_register_toolchains targets
nodejs_register_toolchains(
    name = "node16",
    node_version = "16.20.2",
)

nodejs_register_toolchains(
    name = "node16_nvmrc",
    node_version_from_nvmrc = "//:.nvmrc",
)
