// Rollup configuration
// GENERATED BY Bazel

const rollup = require('rollup');
const {resolveBazel, banner, onwarn, plugins} = require(TMPL_bazel_rollup_conf_path);

module.exports = {
  resolveBazel,
  banner,
  onwarn,
  output: {
    format: 'TMPL_output_format',
    name: 'TMPL_global_name',
  },
  plugins,
}
