workspace(name = "bazel_workspaces_compat")

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../bazel-bin/local_testing_package",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "yarn_install")

yarn_install(
    name = "npm",
    # Need to a reference to this workspace in data so that
    # the external/bazel_workspaces is setup before yarn_install runs
    data = ["@bazel_workspaces_compat//:package.json"],
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")

install_bazel_dependencies()
