workspace(name = "node_loader_e2e_no_preserve_symlinks")

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../..",
)

load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")

rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

node_repositories(
  package_json = ["//:package.json"],
  preserve_symlinks = False,
)

yarn_install(
    name = "node_loader_e2e_no_preserve_symlinks_deps",
    package_json = "//deps:package.json",
    yarn_lock = "//deps:yarn.lock",
)
