workspace(
    name = "node_loader_e2e_no_preserve_symlinks",
    managed_directories = {
        "@npm": ["node_modules"],
    },
)

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../dist/build_bazel_rules_nodejs/release",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

node_repositories(preserve_symlinks = False)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
