# Copyright 2019 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "examples_vendored_node_and_yarn")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "c2ad51299792d5af3b258f1dd71b3b57eff9424c2e1797d9c1d65717d95da03a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.7.3/rules_nodejs-5.7.3.tar.gz"],
)

load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")

build_bazel_rules_nodejs_dependencies()

# See comment in README about these fetches
http_archive(
    name = "vendored_node_linux_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "cc9c3eed21755b490e5333ccab208ce15b539c35f64a764eeeae77c58746a7ff",
    strip_prefix = "node-v15.0.1-linux-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-linux-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_darwin_amd64",
    build_file_content = """exports_files(["bin/node"])""",
    sha256 = "78571df5b35d3ec73d7543332776bcb8cab3bc0e3abd12b1440fbcd01c74c055",
    strip_prefix = "node-v15.0.1-darwin-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-darwin-x64.tar.xz"],
)

http_archive(
    name = "vendored_node_windows_amd64",
    build_file_content = """exports_files(["node.exe"])""",
    sha256 = "efa7a74d91789a6e9f068f375e49f108ff87578fd88ff4b4e7fefd930c04db6c",
    strip_prefix = "node-v15.0.1-win-x64",
    urls = ["https://nodejs.org/dist/v15.0.1/node-v15.0.1-win-x64.zip"],
)

http_archive(
    name = "vendored_yarn_1_10_0",
    build_file_content = """exports_files(["bin/yarn.js"])""",
    sha256 = "83277bd505c7f4009c13077266020c97298727de7edf67af5ca66eccae9d4632",
    strip_prefix = "yarn-v1.10.0",
    urls = ["https://github.com/yarnpkg/yarn/releases/download/v1.10.0/yarn-v1.10.0.tar.gz"],
)

register_toolchains("//toolchains:all")

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm",
    exports_directories_only = False,
    node_repository = "vendored_node",
    package_json = "//:package.json",
    yarn = "@vendored_yarn_1_10_0//:bin/yarn.js",
    yarn_lock = "//:yarn.lock",
)
