workspace(name = "program_example")

http_archive(
    name = "bazel_skylib",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/0.3.1.zip",
    strip_prefix = "bazel-skylib-0.3.1",
    sha256 = "95518adafc9a2b656667bbf517a952e54ce7f350779d0dd95133db4eb5c27fb1",
)

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../..",
)
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

# Install a hermetic version of node.
# After this is run, these labels will be available:
# - NodeJS:
#   @nodejs//:node
# - NPM:
#   @nodejs//:npm
# - The yarn package manager:
#   @nodejs//:yarn
node_repositories(package_json = ["//:package.json"], node_version = "8.11.1", yarn_version = "1.5.1")

# Now the user must run either
# bazel run @nodejs//:yarn
# or
# bazel run @nodejs//:npm
