name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **rules_nodejs is mostly unmaintained!**
        
        Only the "core" module (code under the /nodejs folder) is maintained by volunteers from Aspect.dev.
        This includes only the nodejs toolchain and a few Provider types.

        If you're having an issue with anything else, you can still file it but you shouldn't expect any help.

        If you're looking for support, try the `#javascript` channel on [Bazel slack](https://slack.bazel.build).

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: Please tell us about your environment
      value: |
        Development (host) and target OS/architectures:

        Output of `bazel --version`:

        Version of rules_nodejs, or other relevant rules from your
        `WORKSPACE` or `MODULE.bazel` file:

        Language(s) and/or frameworks involved:
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Your bug is more likely to be resolved if you provide the steps to reproduce, and if possible a minimal demo of the problem.
      render: shell

  - type: textarea
    id: other
    attributes:
      label: Any other information?
      description: |
        (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, things you've tried, links for us to have context, eg. stackoverflow, gitter, etc)
