"Listing of all e2e tests, used to set up their repositories in /WORKSPACE"
ALL_E2E = [
    "bazel_managed_deps",
    "fine_grained_symlinks",
    "jasmine",
    "karma",
    "karma_stack_trace",
    "karma_typescript",
    "less",
    "node_loader_no_preserve_symlinks",
    "node_loader_preserve_symlinks",
    "packages",
    "rollup",
    "stylus",
    "symlinked_node_modules_npm",
    "symlinked_node_modules_yarn",
    "terser",
    "ts_auto_deps",
    "ts_devserver",
    "typescript",
    "webpack",
]
