# Copyright 2019 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#This contains references to the symbols we want documented.
#We can't point stardoc to the top-level index.bzl since then it will see macros rather than the rules they wrap.
#So this is a copy of index.bzl with macro indirection removed.

"""
# TypeScript rules for Bazel

The TypeScript rules integrate the TypeScript compiler with Bazel.

## Alternatives

The `@build_bazel_rules_nodejs` Bazel module provides Bazel wrappers around the TypeScript compiler.

At a high level, there are three alternatives provided.
This section describes the trade-offs between these rules.

### Option 1: tsc

`tsc` is the TypeScript compiler published by the team at Microsoft.
You can call it without any custom Bazel rules.

The only reason to use raw `tsc` is if you want to compile a directory of `.ts` files and cannot enumerate them ahead-of-time in your BUILD file so that Bazel can predict all the output files.
(For example if the `.ts` files are generated by some tool).
This will produce an opaque directory of `.js` file outputs, which you won't be able to individually reference.

Any other use case for `tsc` is better served by using `ts_project`, see below.

Like we do for any npm package that exposes a binary, rules_nodejs will see your dependency on
`typescript` and will generate an `index.bzl` file allowing you to run `tsc`.
To use it, add the load statement `load("@npm//typescript:index.bzl", "tsc")` to your BUILD file.
(Possibly replacing `@npm` with the name of the repository where you installed dependencies)

Then call it, using the [`npm_package_bin`](Built-ins#npm_package_bin) documentation.

Here is an example:
https://github.com/bazelbuild/rules_nodejs/blob/3.2.2/internal/node/test/BUILD.bazel#L491-L507

### Option 2: tsc_test

`tsc_test` is generated alongside `tsc`.
It is identical, except that Bazel treats it as a test target, producing only an exit code
rather than files to be consumed by other steps in the build.

This can be used for a build with `--noEmit`, so that TypeScript is purely used for
type-checking and not for producing any build outputs. However, the `transpiler`
attribute of `ts_project` is generally better for this use case, as it allows configuration
of the transpiler and type-checker in a single Bazel rule.

To use it, add the load statement `load("@npm//typescript:index.bzl", "tsc_test")` to your BUILD file.
(Possibly replacing `@npm` with the name of the repository where you installed dependencies)

To get the typings available in the test (as "runfiles"), you may need to gather them from dependencies if they
are not included as default outputs of those dependencies, like so:

```starlark
filegroup(name = "types", srcs = ["//some:js_library"], output_group = "types")
```

And then include the `:types` target in the `data` of the `tsc_test`.

See example in https://github.com/bazelbuild/rules_nodejs/tree/stable/ts/tests/tsc_test

### Option 3: ts_project

`ts_project` simply runs `tsc --project`, with Bazel knowing which outputs to expect based on the TypeScript compiler options,
and with interoperability with other TypeScript rules via the [DeclarationInfo] Provider that transmits the type information.

It is intended as an easy on-boarding for existing TypeScript code and should be familiar if your background is in frontend ecosystem idioms.

Any behavior of `ts_project` should be reproducible outside of Bazel, with a couple of caveats noted in the rule documentation below.

Exhaustive examples of calling `ts_project` are in the test suite:
https://github.com/bazelbuild/rules_nodejs/tree/stable/ts/tests

And there are also many uses of it in our <examples>

[DeclarationInfo]: Built-ins#declarationinfo

## Installation

In your WORKSPACE file, fetch the TypeScript npm package:

```starlark
load("//ts:repositories.bzl", "ts_repositories")

ts_repositories(
    ts_version = "4.3.5",
    # This allows Bazel to cache the 10M download. Compute with:
    # curl https://registry.npmjs.org/typescript/-/typescript-4.3.5.tgz | shasum -a 256
    sha256 = "c7be550da858be7abfc73dd0b9060ab23ce835ae3b05931f4500a25c09766d45",
)
```

You should ensure the version of TypeScript used by Bazel matches your project or editor setup,
so that you don't get different results.

## Typical Usage

The `ts_project` rule invokes the TypeScript compiler on one compilation unit,
or "library" (generally one directory of source files). In TypeScript terms, this is one "Project"
which can use "Project References" to break up a large application.

Create a `BUILD` file next to your sources:

```starlark
load("@build_bazel_rules_nodejs//ts:ts_project.bzl", "ts_project")

ts_project(
    name = "my_code",
    # glob is a quick way to select all the code,
    # but has performance penalty in that Bazel must evaluate it.
    srcs = glob(["*.ts"]),
    deps = ["//path/to/other:library"],
)
```

Here, `//path/to/other:library` is another target in your repo that produces TypeScript typings (for example, another `ts_project` rule).
Be sure to set the `rootDirs` in your tsconfig.json as noted below, so that TypeScript can find the `.d.ts` files produced by that other target.

To use third-party libraries from npm, first install them (likely using `npm_install` or `yarn_install` rules) then add those to the `deps` as well:

```starlark
ts_project(
    name = "my_code",
    srcs = glob(["*.ts"]),
    deps = [
      "@npm//@types/node",
      "@npm//@types/foo",
      "@npm//somelib",
      "//path/to/other:library",
    ],
)
```

You can also use the `@npm//@types` grouping target which will include all
packages in the `@types` scope as dependencies.

To build a `ts_library` target run:

`bazel build //path/to/package:target`

Note that the `tsconfig.json` file used for compilation should be the same one
your editor references, or `extends` from it, to keep consistent settings for the TypeScript compiler.

Anything you do with TypeScript is possible with `ts_project`, including json imports, type-checking only,
transpile only, outdir, rootdir, and so on.

> To use `ts_project` for typecheck-only, you'll still need to use --declaration so that .d.ts files are produced.
> The `transpiler` attribute then allows you to use some other tool to transpile the .js files.
> Alternatively, see the `tsc_test` rule documented above.

See many examples in our test cases:
https://github.com/bazelbuild/rules_nodejs/tree/stable/ts/tests
"""

load(":ts_config.bzl", _ts_config = "ts_config")
load(":ts_project.bzl", _ts_project = "ts_project")

ts_config = _ts_config
ts_project = _ts_project
