bazel run //packages/rollup/test/integration:test_amd.update
bazel run //packages/rollup/test/integration:test_cjs.update
bazel run //packages/rollup/test/integration:test_esm.update
bazel run //packages/rollup/test/integration:test_iife.update
bazel run //packages/rollup/test/integration:test_system.update
bazel run //packages/rollup/test/integration:test_umd.update
bazel run //packages/rollup/test/integration:test_amd_map_sha256.update
bazel run //packages/rollup/test/integration:test_cjs_map_sha256.update
bazel run //packages/rollup/test/integration:test_esm_map_sha256.update
bazel run //packages/rollup/test/integration:test_iife_map_sha256.update
bazel run //packages/rollup/test/integration:test_system_map_sha256.update
bazel run //packages/rollup/test/integration:test_umd_map_sha256.update
bazel run //packages/rollup/test/integration:test_umd_sha256.update
