# Copyright 2019 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(
    name = "examples_cypress",
    managed_directories = {"@yarn": ["node_modules"]},
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "0fa2d443571c9e02fcb7363a74ae591bdcce2dd76af8677a95965edf329d778a",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/3.6.0/rules_nodejs-3.6.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "yarn",
    # TODO(dan?): figure out why this fails:
    # ERROR: /private/tmp/tmp-96111FZPjEFtem0Q1/BUILD.bazel:38:17:
    # no such target '@yarn//:node_modules/cypress/bin/cypress':
    # target 'node_modules/cypress/bin/cypress' not declared in package '';
    # however, a source file of this name exists.
    # (Perhaps add 'exports_files(["node_modules/cypress/bin/cypress"])' to /BUILD?)
    # defined by /private/var/tmp/_bazel_buildkite/123/external/yarn/BUILD.bazel and referenced by '//:test'
    exports_directories_only = False,
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@yarn//@bazel/cypress:index.bzl", "cypress_repository")

cypress_repository(
    name = "cypress",
    cypress_bin = "@yarn//:node_modules/cypress/bin/cypress",
)
