workspace(name = "fine_grained_symlinks")

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../dist/build_bazel_rules_nodejs/release",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

# This test needs to run with yarn 1.9.2 to test the fix for
# https://github.com/bazelbuild/rules_nodejs/issues/438 and
# https://github.com/bazelbuild/rules_nodejs/issues/428
node_repositories(
    node_version = "10.3.0",
    package_json = ["//:package.json"],
    yarn_version = "1.9.2",
)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
