workspace(
    name = "node_loader_e2e_preserve_symlinks",
    managed_directories = {
        "@node_loader_e2e_preserve_symlinks_deps": ["deps/node_modules"],
    },
)

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../dist/build_bazel_rules_nodejs/release",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

node_repositories(
    package_json = ["//:package.json"],
    preserve_symlinks = True,
)

yarn_install(
    name = "node_loader_e2e_preserve_symlinks_deps",
    package_json = "//deps:package.json",
    yarn_lock = "//deps:yarn.lock",
)
