repository: bazelbuild/rules_nodejs
plugins:
  - "jekyll-toc"

# jekyll-toc settings
toc:
  min_level: 2
  max_level: 3

defaults:
  -
    values:
      # Enable table of contents for every page
      toc: true

highlighter: rouge
baseurl: /rules_nodejs
