load("//:defs.bzl", "js_library")

js_library(
    name = "global_css",
    srcs = ["global.css"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "index_css",
    srcs = ["index.css"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "utils.module_css",
    srcs = ["utils.module.css"],
    visibility = ["//visibility:public"],
)
