workspace(name = "examples_relative_data")

# In your code, you'd fetch this repository with an `http_archive` call.
# We do this local repository only because this example lives in the same
# repository with the rules_nodejs code and we want to test them together.
local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../dist/build_bazel_rules_nodejs/release",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "yarn_install")
load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

# This runs yarn install, then our generate_build_file.js to create BUILD files
# inside the resulting node_modules directory.
# The name "npm" here means the resulting modules are referenced like
# @npm//jasmine
yarn_install(
    name = "npm",
    data = [
        "//:subdir/example.sh"
    ],
    package_json = "//:subdir/package.json",
    yarn_lock = "//:subdir/yarn.lock",
)
node_repositories(
    node_version = "8.11.1",
    package_json = ["//:subdir/package.json"],
    yarn_version = "1.5.1",
)
